### PR TITLE
Upgrade Squeak32 from 5.1 to 5.2; add Squeak64-5.2

### PR DESCRIPTION
**Pull request by fniephaus**
The default VM for Squeak 5.2 uses a heartbeat thread (AWFY used an itimer VM before).

### CODE REVIEW

**Comment by fniephaus** [comment]
Looks like this breaks RSqueak which is still 32bit. @krono @timfel does it make sense to update RSqueak to 64bit or shall we keep the 32bit version for now?

**Comment by krono** [comment]
Strange. RSqueak can compile as 64 for some time now and reads 32 and 64 images just fine, as far as I remember…

**Comment by timfel** [comment]
No, we read only 32bit images. We just convert them to pseudo 64bits on the fly
________________________________

**Comment by fniephaus** [comment]
Ok, I've renamed `Squeak` to `Squeak32` and added `Squeak64`. 64bit performance should be better due to larger `SmallInteger`s and `SmallFloat64`s.

**Comment by fniephaus** [comment]
I think I'm done cleaning everything up...[RSqueak](https://travis-ci.org/smarr/are-we-fast-yet/jobs/528184881#L2089) failed when executing the `CD` benchmark (which is why it's probably listed as allowed failure), the Ruby build failed due to a [code style problem](https://travis-ci.org/smarr/are-we-fast-yet/jobs/528184879#L702), and Lua failed due to some [unrelated error](https://travis-ci.org/smarr/are-we-fast-yet/jobs/528184880#L888).

**Comment by fniephaus** [comment]
I'd say this can be merged :)

**Comment by smarr** [comment]
Thanks! Rebased and merged, and CI is green 😄

**Comment by fniephaus** [comment]
Great, thanks!

**Pull request merged**
