### PR TITLE
Add verification results for CD w/ numAircrafts=2

### PR DESCRIPTION
**Pull request by fniephaus**

### CODE REVIEW

**Comment by smarr** [comment]
Just checking, you did try this on 2 or more of the languages?

**Comment by fniephaus** [comment]
```
$ ruby harness.rb CD 1 2
Starting CD benchmark ...
CD: iterations=1 runtime: 12780us
CD: iterations=1 average: 12780us total: 12780us
```

```
$ node harness.js CD 1 2
Starting CD benchmark ...
CD: iterations=1 runtime: 17678us
CD: iterations=1 average: 17678us total: 17678us
```

Smalltalk works too. The CI job failures seem to be unrelated, maybe restart them?

**Comment by smarr** [comment]
Thanks, just wanted to be sure it's the correct value. I didn't check :)

CI failures are expected: out of date URL, and a rubocop update breaking current config.
No blockers.

**Comment by fniephaus** [comment]
Thanks for the merge!

**Pull request merged**
